/************************************************************************
 * COPYRIGHT (C) Ericsson 2012                                           *
 * The copyright to the computer program(s) herein is the property       *
 * of Telefonaktiebolaget LM Ericsson.                                   *
 * The program(s) may be used and/or copied only with the written        *
 * permission from Telefonaktiebolaget LM Ericsson or in accordance with *
 * the terms and conditions stipulated in the agreement/contract         *
 * under which the program(s) have been supplied.                        *
 *************************************************************************
 *************************************************************************
 * File: gtpv1_message_types.c
 * Date: Mar 19, 2012
 * Author: LMI/LXR/SH Liam Fallon
 ************************************************************************/

/**
 * This module manages GTP V1 message types
 */

#include <string.h>
#include <gtpv1_message_types.h>

// Hold all GTP V1 message types
struct gtpv1_message_type gtpv1_message_types[MAX_GTPV1_MESSAGE_TYPES];

//
// This function initializes static data for GTP V1 messages
//
void init_gtpv1_message_types()
{
	// Zero the message types
	for (int i = 0; i < MAX_GTPV1_MESSAGE_TYPES; i++) {
		gtpv1_message_types[i].id = 0;
		strcpy(gtpv1_message_types[i].name, "");
	}

	// Set up the message types
	gtpv1_message_types[GTPV1_MT_ECHO_REQUEST].id = GTPV1_MT_ECHO_REQUEST;
	strcpy(gtpv1_message_types[GTPV1_MT_ECHO_REQUEST].name, "ECHO_REQUEST");

	gtpv1_message_types[GTPV1_MT_ECHO_RESPONSE].id = GTPV1_MT_ECHO_RESPONSE;
	strcpy(gtpv1_message_types[GTPV1_MT_ECHO_RESPONSE].name, "ECHO_RESPONSE");

	gtpv1_message_types[GTPV1_MT_VERSION_NOT_SUPPORTED].id = GTPV1_MT_VERSION_NOT_SUPPORTED;
	strcpy(gtpv1_message_types[GTPV1_MT_VERSION_NOT_SUPPORTED].name, "VERSION_NOT_SUPPORTED");

	gtpv1_message_types[GTPV1_MT_NODE_ALIVE_REQUEST].id = GTPV1_MT_NODE_ALIVE_REQUEST;
	strcpy(gtpv1_message_types[GTPV1_MT_NODE_ALIVE_REQUEST].name, "NODE_ALIVE_REQUEST");

	gtpv1_message_types[GTPV1_MT_NODE_ALIVE_RESPONSE].id = GTPV1_MT_NODE_ALIVE_RESPONSE;
	strcpy(gtpv1_message_types[GTPV1_MT_NODE_ALIVE_RESPONSE].name, "NODE_ALIVE_RESPONSE");

	gtpv1_message_types[GTPV1_MT_REDIRECTION_REQUEST].id = GTPV1_MT_REDIRECTION_REQUEST;
	strcpy(gtpv1_message_types[GTPV1_MT_REDIRECTION_REQUEST].name, "REDIRECTION_REQUEST");

	gtpv1_message_types[GTPV1_MT_REDIRECTION_RESPONSE].id = GTPV1_MT_REDIRECTION_RESPONSE;
	strcpy(gtpv1_message_types[GTPV1_MT_REDIRECTION_RESPONSE].name, "REDIRECTION_RESPONSE");

	gtpv1_message_types[GTPV1_MT_CREATE_PDP_CONTEXT_REQUEST].id = GTPV1_MT_CREATE_PDP_CONTEXT_REQUEST;
	strcpy(gtpv1_message_types[GTPV1_MT_CREATE_PDP_CONTEXT_REQUEST].name, "CREATE_PDP_CONTEXT_REQUEST");

	gtpv1_message_types[GTPV1_MT_CREATE_PDP_CONTEXT_RESPONSE].id = GTPV1_MT_CREATE_PDP_CONTEXT_RESPONSE;
	strcpy(gtpv1_message_types[GTPV1_MT_CREATE_PDP_CONTEXT_RESPONSE].name, "CREATE_PDP_CONTEXT_RESPONSE");

	gtpv1_message_types[GTPV1_MT_UPDATE_PDP_CONTEXT_REQUEST].id = GTPV1_MT_UPDATE_PDP_CONTEXT_REQUEST;
	strcpy(gtpv1_message_types[GTPV1_MT_UPDATE_PDP_CONTEXT_REQUEST].name, "UPDATE_PDP_CONTEXT_REQUEST");

	gtpv1_message_types[GTPV1_MT_UPDATE_PDP_CONTEXT_RESPONSE].id = GTPV1_MT_UPDATE_PDP_CONTEXT_RESPONSE;
	strcpy(gtpv1_message_types[GTPV1_MT_UPDATE_PDP_CONTEXT_RESPONSE].name, "UPDATE_PDP_CONTEXT_RESPONSE");

	gtpv1_message_types[GTPV1_MT_DELETE_PDP_CONTEXT_REQUEST].id = GTPV1_MT_DELETE_PDP_CONTEXT_REQUEST;
	strcpy(gtpv1_message_types[GTPV1_MT_DELETE_PDP_CONTEXT_REQUEST].name, "DELETE_PDP_CONTEXT_REQUEST");

	gtpv1_message_types[GTPV1_MT_DELETE_PDP_CONTEXT_RESPONSE].id = GTPV1_MT_DELETE_PDP_CONTEXT_RESPONSE;
	strcpy(gtpv1_message_types[GTPV1_MT_DELETE_PDP_CONTEXT_RESPONSE].name, "DELETE_PDP_CONTEXT_RESPONSE");

	gtpv1_message_types[GTPV1_MT_INITIATE_PDP_CONTEXT_ACTIVATION_REQUEST].id = GTPV1_MT_INITIATE_PDP_CONTEXT_ACTIVATION_REQUEST;
	strcpy(gtpv1_message_types[GTPV1_MT_INITIATE_PDP_CONTEXT_ACTIVATION_REQUEST].name, "INITIATE_PDP_CONTEXT_ACTIVATION_REQUEST");

	gtpv1_message_types[GTPV1_MT_INITIATE_PDP_CONTEXT_ACTIVATION_RESPONSE].id = GTPV1_MT_INITIATE_PDP_CONTEXT_ACTIVATION_RESPONSE;
	strcpy(gtpv1_message_types[GTPV1_MT_INITIATE_PDP_CONTEXT_ACTIVATION_RESPONSE].name, "INITIATE_PDP_CONTEXT_ACTIVATION_RESPONSE");

	gtpv1_message_types[GTPV1_MT_ERROR_INDICATION].id = GTPV1_MT_ERROR_INDICATION;
	strcpy(gtpv1_message_types[GTPV1_MT_ERROR_INDICATION].name, "ERROR_INDICATION");

	gtpv1_message_types[GTPV1_MT_PDU_NOTIFICATION_REQUEST].id = GTPV1_MT_PDU_NOTIFICATION_REQUEST;
	strcpy(gtpv1_message_types[GTPV1_MT_PDU_NOTIFICATION_REQUEST].name, "PDU_NOTIFICATION_REQUEST");

	gtpv1_message_types[GTPV1_MT_PDU_NOTIFICATION_RESPONSE].id = GTPV1_MT_PDU_NOTIFICATION_RESPONSE;
	strcpy(gtpv1_message_types[GTPV1_MT_PDU_NOTIFICATION_RESPONSE].name, "PDU_NOTIFICATION_RESPONSE");

	gtpv1_message_types[GTPV1_MT_PDU_NOTIFICATION_REJECT_REQUEST].id = GTPV1_MT_PDU_NOTIFICATION_REJECT_REQUEST;
	strcpy(gtpv1_message_types[GTPV1_MT_PDU_NOTIFICATION_REJECT_REQUEST].name, "PDU_NOTIFICATION_REJECT_REQUEST");

	gtpv1_message_types[GTPV1_MT_PDU_NOTIFICATION_REJECT_RESPONSE].id = GTPV1_MT_PDU_NOTIFICATION_REJECT_RESPONSE;
	strcpy(gtpv1_message_types[GTPV1_MT_PDU_NOTIFICATION_REJECT_RESPONSE].name, "PDU_NOTIFICATION_REJECT_RESPONSE");

	gtpv1_message_types[GTPV1_MT_SUPPORTED_EXTENSION_HEADERS_NOTIFICATION].id = GTPV1_MT_SUPPORTED_EXTENSION_HEADERS_NOTIFICATION;
	strcpy(gtpv1_message_types[GTPV1_MT_SUPPORTED_EXTENSION_HEADERS_NOTIFICATION].name, "SUPPORTED_EXTENSION_HEADERS_NOTIFICATION");

	gtpv1_message_types[GTPV1_MT_SEND_ROUTEING_INFORMATION_FOR_GPRS_REQUEST].id = GTPV1_MT_SEND_ROUTEING_INFORMATION_FOR_GPRS_REQUEST;
	strcpy(gtpv1_message_types[GTPV1_MT_SEND_ROUTEING_INFORMATION_FOR_GPRS_REQUEST].name, "SEND_ROUTEING_INFORMATION_FOR_GPRS_REQUEST");

	gtpv1_message_types[GTPV1_MT_SEND_ROUTEING_INFORMATION_FOR_GPRS_RESPONSE].id = GTPV1_MT_SEND_ROUTEING_INFORMATION_FOR_GPRS_RESPONSE;
	strcpy(gtpv1_message_types[GTPV1_MT_SEND_ROUTEING_INFORMATION_FOR_GPRS_RESPONSE].name, "SEND_ROUTEING_INFORMATION_FOR_GPRS_RESPONSE");

	gtpv1_message_types[GTPV1_MT_FAILURE_REPORT_REQUEST].id = GTPV1_MT_FAILURE_REPORT_REQUEST;
	strcpy(gtpv1_message_types[GTPV1_MT_FAILURE_REPORT_REQUEST].name, "FAILURE_REPORT_REQUEST");

	gtpv1_message_types[GTPV1_MT_FAILURE_REPORT_RESPONSE].id = GTPV1_MT_FAILURE_REPORT_RESPONSE;
	strcpy(gtpv1_message_types[GTPV1_MT_FAILURE_REPORT_RESPONSE].name, "FAILURE_REPORT_RESPONSE");

	gtpv1_message_types[GTPV1_MT_NOTE_MS_GPRS_PRESENT_REQUEST].id = GTPV1_MT_NOTE_MS_GPRS_PRESENT_REQUEST;
	strcpy(gtpv1_message_types[GTPV1_MT_NOTE_MS_GPRS_PRESENT_REQUEST].name, "NOTE_MS_GPRS_PRESENT_REQUEST");

	gtpv1_message_types[GTPV1_MT_NOTE_MS_GPRS_PRESENT_RESPONSE].id = GTPV1_MT_NOTE_MS_GPRS_PRESENT_RESPONSE;
	strcpy(gtpv1_message_types[GTPV1_MT_NOTE_MS_GPRS_PRESENT_RESPONSE].name, "NOTE_MS_GPRS_PRESENT_RESPONSE");

	gtpv1_message_types[GTPV1_MT_IDENTIFICATION_REQUEST].id = GTPV1_MT_IDENTIFICATION_REQUEST;
	strcpy(gtpv1_message_types[GTPV1_MT_IDENTIFICATION_REQUEST].name, "IDENTIFICATION_REQUEST");

	gtpv1_message_types[GTPV1_MT_IDENTIFICATION_RESPONSE].id = GTPV1_MT_IDENTIFICATION_RESPONSE;
	strcpy(gtpv1_message_types[GTPV1_MT_IDENTIFICATION_RESPONSE].name, "IDENTIFICATION_RESPONSE");

	gtpv1_message_types[GTPV1_MT_SGSN_CONTEXT_REQUEST].id = GTPV1_MT_SGSN_CONTEXT_REQUEST;
	strcpy(gtpv1_message_types[GTPV1_MT_SGSN_CONTEXT_REQUEST].name, "SGSN_CONTEXT_REQUEST");

	gtpv1_message_types[GTPV1_MT_SGSN_CONTEXT_RESPONSE].id = GTPV1_MT_SGSN_CONTEXT_RESPONSE;
	strcpy(gtpv1_message_types[GTPV1_MT_SGSN_CONTEXT_RESPONSE].name, "SGSN_CONTEXT_RESPONSE");

	gtpv1_message_types[GTPV1_MT_SGSN_CONTEXT_ACKNOWLEDGE].id = GTPV1_MT_SGSN_CONTEXT_ACKNOWLEDGE;
	strcpy(gtpv1_message_types[GTPV1_MT_SGSN_CONTEXT_ACKNOWLEDGE].name, "SGSN_CONTEXT_ACKNOWLEDGE");

	gtpv1_message_types[GTPV1_MT_FORWARD_RELOCATION_REQUEST].id = GTPV1_MT_FORWARD_RELOCATION_REQUEST;
	strcpy(gtpv1_message_types[GTPV1_MT_FORWARD_RELOCATION_REQUEST].name, "FORWARD_RELOCATION_REQUEST");

	gtpv1_message_types[GTPV1_MT_FORWARD_RELOCATION_RESPONSE].id = GTPV1_MT_FORWARD_RELOCATION_RESPONSE;
	strcpy(gtpv1_message_types[GTPV1_MT_FORWARD_RELOCATION_RESPONSE].name, "FORWARD_RELOCATION_RESPONSE");

	gtpv1_message_types[GTPV1_MT_FORWARD_RELOCATION_COMPLETE].id = GTPV1_MT_FORWARD_RELOCATION_COMPLETE;
	strcpy(gtpv1_message_types[GTPV1_MT_FORWARD_RELOCATION_COMPLETE].name, "FORWARD_RELOCATION_COMPLETE");

	gtpv1_message_types[GTPV1_MT_RELOCATION_CANCEL_REQUEST].id = GTPV1_MT_RELOCATION_CANCEL_REQUEST;
	strcpy(gtpv1_message_types[GTPV1_MT_RELOCATION_CANCEL_REQUEST].name, "RELOCATION_CANCEL_REQUEST");

	gtpv1_message_types[GTPV1_MT_RELOCATION_CANCEL_RESPONSE].id = GTPV1_MT_RELOCATION_CANCEL_RESPONSE;
	strcpy(gtpv1_message_types[GTPV1_MT_RELOCATION_CANCEL_RESPONSE].name, "RELOCATION_CANCEL_RESPONSE");

	gtpv1_message_types[GTPV1_MT_FORWARD_SRNS_CONTEXT].id = GTPV1_MT_FORWARD_SRNS_CONTEXT;
	strcpy(gtpv1_message_types[GTPV1_MT_FORWARD_SRNS_CONTEXT].name, "FORWARD_SRNS_CONTEXT");

	gtpv1_message_types[GTPV1_MT_FORWARD_RELOCATION_COMPLETE_ACKNOWLEDGE].id = GTPV1_MT_FORWARD_RELOCATION_COMPLETE_ACKNOWLEDGE;
	strcpy(gtpv1_message_types[GTPV1_MT_FORWARD_RELOCATION_COMPLETE_ACKNOWLEDGE].name, "FORWARD_RELOCATION_COMPLETE_ACKNOWLEDGE");

	gtpv1_message_types[GTPV1_MT_FORWARD_SRNS_CONTEXT_ACKNOWLEDGE].id = GTPV1_MT_FORWARD_SRNS_CONTEXT_ACKNOWLEDGE;
	strcpy(gtpv1_message_types[GTPV1_MT_FORWARD_SRNS_CONTEXT_ACKNOWLEDGE].name, "FORWARD_SRNS_CONTEXT_ACKNOWLEDGE");

	gtpv1_message_types[GTPV1_MT_RAN_INFORMATION_RELAY].id = GTPV1_MT_RAN_INFORMATION_RELAY;
	strcpy(gtpv1_message_types[GTPV1_MT_RAN_INFORMATION_RELAY].name, "RAN_INFORMATION_RELAY");

	gtpv1_message_types[GTPV1_MT_MBMS_NOTIFICATION_REQUEST].id = GTPV1_MT_MBMS_NOTIFICATION_REQUEST;
	strcpy(gtpv1_message_types[GTPV1_MT_MBMS_NOTIFICATION_REQUEST].name, "MBMS_NOTIFICATION_REQUEST");

	gtpv1_message_types[GTPV1_MT_MBMS_NOTIFICATION_RESPONSE].id = GTPV1_MT_MBMS_NOTIFICATION_RESPONSE;
	strcpy(gtpv1_message_types[GTPV1_MT_MBMS_NOTIFICATION_RESPONSE].name, "MBMS_NOTIFICATION_RESPONSE");

	gtpv1_message_types[GTPV1_MT_MBMS_NOTIFICATION_REJECT_REQUEST].id = GTPV1_MT_MBMS_NOTIFICATION_REJECT_REQUEST;
	strcpy(gtpv1_message_types[GTPV1_MT_MBMS_NOTIFICATION_REJECT_REQUEST].name, "MBMS_NOTIFICATION_REJECT_REQUEST");

	gtpv1_message_types[GTPV1_MT_MBMS_NOTIFICATION_REJECT_RESPONSE].id = GTPV1_MT_MBMS_NOTIFICATION_REJECT_RESPONSE;
	strcpy(gtpv1_message_types[GTPV1_MT_MBMS_NOTIFICATION_REJECT_RESPONSE].name, "MBMS_NOTIFICATION_REJECT_RESPONSE");

	gtpv1_message_types[GTPV1_MT_CREATE_MBMS_CONTEXT_REQUEST].id = GTPV1_MT_CREATE_MBMS_CONTEXT_REQUEST;
	strcpy(gtpv1_message_types[GTPV1_MT_CREATE_MBMS_CONTEXT_REQUEST].name, "CREATE_MBMS_CONTEXT_REQUEST");

	gtpv1_message_types[GTPV1_MT_CREATE_MBMS_CONTEXT_RESPONSE].id = GTPV1_MT_CREATE_MBMS_CONTEXT_RESPONSE;
	strcpy(gtpv1_message_types[GTPV1_MT_CREATE_MBMS_CONTEXT_RESPONSE].name, "CREATE_MBMS_CONTEXT_RESPONSE");

	gtpv1_message_types[GTPV1_MT_UPDATE_MBMS_CONTEXT_REQUEST].id = GTPV1_MT_UPDATE_MBMS_CONTEXT_REQUEST;
	strcpy(gtpv1_message_types[GTPV1_MT_UPDATE_MBMS_CONTEXT_REQUEST].name, "UPDATE_MBMS_CONTEXT_REQUEST");

	gtpv1_message_types[GTPV1_MT_UPDATE_MBMS_CONTEXT_RESPONSE].id = GTPV1_MT_UPDATE_MBMS_CONTEXT_RESPONSE;
	strcpy(gtpv1_message_types[GTPV1_MT_UPDATE_MBMS_CONTEXT_RESPONSE].name, "UPDATE_MBMS_CONTEXT_RESPONSE");

	gtpv1_message_types[GTPV1_MT_DELETE_MBMS_CONTEXT_REQUEST].id = GTPV1_MT_DELETE_MBMS_CONTEXT_REQUEST;
	strcpy(gtpv1_message_types[GTPV1_MT_DELETE_MBMS_CONTEXT_REQUEST].name, "DELETE_MBMS_CONTEXT_REQUEST");

	gtpv1_message_types[GTPV1_MT_DELETE_MBMS_CONTEXT_RESPONSE].id = GTPV1_MT_DELETE_MBMS_CONTEXT_RESPONSE;
	strcpy(gtpv1_message_types[GTPV1_MT_DELETE_MBMS_CONTEXT_RESPONSE].name, "DELETE_MBMS_CONTEXT_RESPONSE");

	gtpv1_message_types[GTPV1_MT_MBMS_REGISTRATION_REQUEST].id = GTPV1_MT_MBMS_REGISTRATION_REQUEST;
	strcpy(gtpv1_message_types[GTPV1_MT_MBMS_REGISTRATION_REQUEST].name, "MBMS_REGISTRATION_REQUEST");

	gtpv1_message_types[GTPV1_MT_MBMS_REGISTRATION_RESPONSE].id = GTPV1_MT_MBMS_REGISTRATION_RESPONSE;
	strcpy(gtpv1_message_types[GTPV1_MT_MBMS_REGISTRATION_RESPONSE].name, "MBMS_REGISTRATION_RESPONSE");

	gtpv1_message_types[GTPV1_MT_MBMS_DE_REGISTRATION_REQUEST].id = GTPV1_MT_MBMS_DE_REGISTRATION_REQUEST;
	strcpy(gtpv1_message_types[GTPV1_MT_MBMS_DE_REGISTRATION_REQUEST].name, "MBMS_DE-REGISTRATION_REQUEST");

	gtpv1_message_types[GTPV1_MT_MBMS_DE_REGISTRATION_RESPONSE].id = GTPV1_MT_MBMS_DE_REGISTRATION_RESPONSE;
	strcpy(gtpv1_message_types[GTPV1_MT_MBMS_DE_REGISTRATION_RESPONSE].name, "MBMS_DE-REGISTRATION_RESPONSE");

	gtpv1_message_types[GTPV1_MT_MBMS_SESSION_START_REQUEST].id = GTPV1_MT_MBMS_SESSION_START_REQUEST;
	strcpy(gtpv1_message_types[GTPV1_MT_MBMS_SESSION_START_REQUEST].name, "MBMS_SESSION_START_REQUEST");

	gtpv1_message_types[GTPV1_MT_MBMS_SESSION_START_RESPONSE].id = GTPV1_MT_MBMS_SESSION_START_RESPONSE;
	strcpy(gtpv1_message_types[GTPV1_MT_MBMS_SESSION_START_RESPONSE].name, "MBMS_SESSION_START_RESPONSE");

	gtpv1_message_types[GTPV1_MT_MBMS_SESSION_STOP_REQUEST].id = GTPV1_MT_MBMS_SESSION_STOP_REQUEST;
	strcpy(gtpv1_message_types[GTPV1_MT_MBMS_SESSION_STOP_REQUEST].name, "MBMS_SESSION_STOP_REQUEST");

	gtpv1_message_types[GTPV1_MT_MBMS_SESSION_STOP_RESPONSE].id = GTPV1_MT_MBMS_SESSION_STOP_RESPONSE;
	strcpy(gtpv1_message_types[GTPV1_MT_MBMS_SESSION_STOP_RESPONSE].name, "MBMS_SESSION_STOP_RESPONSE");

	gtpv1_message_types[GTPV1_MT_MBMS_SESSION_UPDATE_REQUEST].id = GTPV1_MT_MBMS_SESSION_UPDATE_REQUEST;
	strcpy(gtpv1_message_types[GTPV1_MT_MBMS_SESSION_UPDATE_REQUEST].name, "MBMS_SESSION_UPDATE_REQUEST");

	gtpv1_message_types[GTPV1_MT_MBMS_SESSION_UPDATE_RESPONSE].id = GTPV1_MT_MBMS_SESSION_UPDATE_RESPONSE;
	strcpy(gtpv1_message_types[GTPV1_MT_MBMS_SESSION_UPDATE_RESPONSE].name, "MBMS_SESSION_UPDATE_RESPONSE");

	gtpv1_message_types[GTPV1_MT_MS_INFO_CHANGE_NOTIFICATION_REQUEST].id = GTPV1_MT_MS_INFO_CHANGE_NOTIFICATION_REQUEST;
	strcpy(gtpv1_message_types[GTPV1_MT_MS_INFO_CHANGE_NOTIFICATION_REQUEST].name, "MS_INFO_CHANGE_NOTIFICATION_REQUEST");

	gtpv1_message_types[GTPV1_MT_MS_INFO_CHANGE_NOTIFICATION_RESPONSE].id = GTPV1_MT_MS_INFO_CHANGE_NOTIFICATION_RESPONSE;
	strcpy(gtpv1_message_types[GTPV1_MT_MS_INFO_CHANGE_NOTIFICATION_RESPONSE].name, "MS_INFO_CHANGE_NOTIFICATION_RESPONSE");

	gtpv1_message_types[GTPV1_MT_DATA_RECORD_TRANSFER_REQUEST].id = GTPV1_MT_DATA_RECORD_TRANSFER_REQUEST;
	strcpy(gtpv1_message_types[GTPV1_MT_DATA_RECORD_TRANSFER_REQUEST].name, "DATA_RECORD_TRANSFER_REQUEST");

	gtpv1_message_types[GTPV1_MT_DATA_RECORD_TRANSFER_RESPONSE].id = GTPV1_MT_DATA_RECORD_TRANSFER_RESPONSE;
	strcpy(gtpv1_message_types[GTPV1_MT_DATA_RECORD_TRANSFER_RESPONSE].name, "DATA_RECORD_TRANSFER_RESPONSE");

	gtpv1_message_types[GTPV1_MT_END_MARKER].id = GTPV1_MT_END_MARKER;
	strcpy(gtpv1_message_types[GTPV1_MT_END_MARKER].name, "END_MARKER");

	gtpv1_message_types[GTPV1_MT_G_PDU].id = GTPV1_MT_G_PDU;
	strcpy(gtpv1_message_types[GTPV1_MT_G_PDU].name, "G-PDU");
}


