/************************************************************************
 * COPYRIGHT (C) Ericsson 2012                                           *
 * The copyright to the computer program(s) herein is the property       *
 * of Telefonaktiebolaget LM Ericsson.                                   *
 * The program(s) may be used and/or copied only with the written        *
 * permission from Telefonaktiebolaget LM Ericsson or in accordance with *
 * the terms and conditions stipulated in the agreement/contract         *
 * under which the program(s) have been supplied.                        *
 *************************************************************************
 *************************************************************************
 * File: gtpv1_message_types.h
 * Date: Mar 18, 2012
 * Author: LMI/LXR/SH Liam Fallon
 ************************************************************************/

/**
 * This module manages GTP V1 message types
 */

#ifndef GTPV1_MESSAGE_TYPES_H_
#define GTPV1_MESSAGE_TYPES_H_

#include <stdio.h>

//
// Constants
//
#define MAX_GTPV1_MESSAGE_TYPES 256

// A GTP V1 message type holder
struct gtpv1_message_type {
	int id;
	char name[BUFSIZ];
};

// All GTP V1 Messages
extern struct gtpv1_message_type gtpv1_message_types[MAX_GTPV1_MESSAGE_TYPES];

//
// This function initializes static data for GTP V1 messages
//
void init_gtpv1_message_types();

// Declare all GTP V1 message types
#define GTPV1_MT_ECHO_REQUEST 1
#define GTPV1_MT_ECHO_RESPONSE 2
#define GTPV1_MT_VERSION_NOT_SUPPORTED 3
#define GTPV1_MT_NODE_ALIVE_REQUEST 4
#define GTPV1_MT_NODE_ALIVE_RESPONSE 5
#define GTPV1_MT_REDIRECTION_REQUEST 6
#define GTPV1_MT_REDIRECTION_RESPONSE 7
#define GTPV1_MT_CREATE_PDP_CONTEXT_REQUEST 16
#define GTPV1_MT_CREATE_PDP_CONTEXT_RESPONSE 17
#define GTPV1_MT_UPDATE_PDP_CONTEXT_REQUEST 18
#define GTPV1_MT_UPDATE_PDP_CONTEXT_RESPONSE 19
#define GTPV1_MT_DELETE_PDP_CONTEXT_REQUEST 20
#define GTPV1_MT_DELETE_PDP_CONTEXT_RESPONSE 21
#define GTPV1_MT_INITIATE_PDP_CONTEXT_ACTIVATION_REQUEST 22
#define GTPV1_MT_INITIATE_PDP_CONTEXT_ACTIVATION_RESPONSE 23
#define GTPV1_MT_ERROR_INDICATION 26
#define GTPV1_MT_PDU_NOTIFICATION_REQUEST 27
#define GTPV1_MT_PDU_NOTIFICATION_RESPONSE 28
#define GTPV1_MT_PDU_NOTIFICATION_REJECT_REQUEST 29
#define GTPV1_MT_PDU_NOTIFICATION_REJECT_RESPONSE 30
#define GTPV1_MT_SUPPORTED_EXTENSION_HEADERS_NOTIFICATION 31
#define GTPV1_MT_SEND_ROUTEING_INFORMATION_FOR_GPRS_REQUEST 32
#define GTPV1_MT_SEND_ROUTEING_INFORMATION_FOR_GPRS_RESPONSE 33
#define GTPV1_MT_FAILURE_REPORT_REQUEST 34
#define GTPV1_MT_FAILURE_REPORT_RESPONSE 35
#define GTPV1_MT_NOTE_MS_GPRS_PRESENT_REQUEST 36
#define GTPV1_MT_NOTE_MS_GPRS_PRESENT_RESPONSE 37
#define GTPV1_MT_IDENTIFICATION_REQUEST 48
#define GTPV1_MT_IDENTIFICATION_RESPONSE 49
#define GTPV1_MT_SGSN_CONTEXT_REQUEST 50
#define GTPV1_MT_SGSN_CONTEXT_RESPONSE 51
#define GTPV1_MT_SGSN_CONTEXT_ACKNOWLEDGE 52
#define GTPV1_MT_FORWARD_RELOCATION_REQUEST 53
#define GTPV1_MT_FORWARD_RELOCATION_RESPONSE 54
#define GTPV1_MT_FORWARD_RELOCATION_COMPLETE 55
#define GTPV1_MT_RELOCATION_CANCEL_REQUEST 56
#define GTPV1_MT_RELOCATION_CANCEL_RESPONSE 57
#define GTPV1_MT_FORWARD_SRNS_CONTEXT 58
#define GTPV1_MT_FORWARD_RELOCATION_COMPLETE_ACKNOWLEDGE 59
#define GTPV1_MT_FORWARD_SRNS_CONTEXT_ACKNOWLEDGE 60
#define GTPV1_MT_RAN_INFORMATION_RELAY 70
#define GTPV1_MT_MBMS_NOTIFICATION_REQUEST 96
#define GTPV1_MT_MBMS_NOTIFICATION_RESPONSE 97
#define GTPV1_MT_MBMS_NOTIFICATION_REJECT_REQUEST 98
#define GTPV1_MT_MBMS_NOTIFICATION_REJECT_RESPONSE 99
#define GTPV1_MT_CREATE_MBMS_CONTEXT_REQUEST 100
#define GTPV1_MT_CREATE_MBMS_CONTEXT_RESPONSE 101
#define GTPV1_MT_UPDATE_MBMS_CONTEXT_REQUEST 102
#define GTPV1_MT_UPDATE_MBMS_CONTEXT_RESPONSE 103
#define GTPV1_IE_TEARDOWN_IND 19
#define GTPV1_MT_DELETE_MBMS_CONTEXT_REQUEST 104
#define GTPV1_MT_DELETE_MBMS_CONTEXT_RESPONSE 105
#define GTPV1_MT_MBMS_REGISTRATION_REQUEST 112
#define GTPV1_MT_MBMS_REGISTRATION_RESPONSE 113
#define GTPV1_MT_MBMS_DE_REGISTRATION_REQUEST 114
#define GTPV1_MT_MBMS_DE_REGISTRATION_RESPONSE 115
#define GTPV1_MT_MBMS_SESSION_START_REQUEST 116
#define GTPV1_MT_MBMS_SESSION_START_RESPONSE 117
#define GTPV1_MT_MBMS_SESSION_STOP_REQUEST 118
#define GTPV1_MT_MBMS_SESSION_STOP_RESPONSE 119
#define GTPV1_MT_MBMS_SESSION_UPDATE_REQUEST 120
#define GTPV1_MT_MBMS_SESSION_UPDATE_RESPONSE 121
#define GTPV1_MT_MS_INFO_CHANGE_NOTIFICATION_REQUEST 128
#define GTPV1_MT_MS_INFO_CHANGE_NOTIFICATION_RESPONSE 129
#define GTPV1_MT_DATA_RECORD_TRANSFER_REQUEST 240
#define GTPV1_MT_DATA_RECORD_TRANSFER_RESPONSE 241
#define GTPV1_MT_END_MARKER 254
#define GTPV1_MT_G_PDU 255

#endif /* GTPV1_MESSAGE_TYPES_H_ */
